version: 2
updates:
  - package-ecosystem: github-actions #パッケージエコシステム
    directory: / #パッケージマニフェストの配置先ディレクトリ
    schedule: #バージョンアップスケジュール
      interval: daily
    ignore: #無視する依存関係
      - dependency-name: actions/uploda-artifact #無視する依存関係
        versions:
          - 4.3.0
          - 4.3.1
      #- dependency-name: 'actions/*'  # アスタリスクは任意文字列にマッチ
      #  update-types: #除外するバージョンアップの種類
      #    - version-update:semver:major