name: Auto patch merge
on: pull_request
jobs:
    merge:
        if: ${{ github.event_name == 'pull_request' }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v4
            - id: meta #依存関係のメタデータ取得
              uses: dependabot/fetch-metadata@v2 #条件分岐でパッチバージョンチェック
            - if: >-
                    ${{ steps.meta.outputs.dependency-type == 'direct:development' && 
                     steps.meta.outputs.update-type != 'version-update:semver-major' }}
              run: |
                    git pr review "${GITHUB_HEAD_REF}" --approve
                    git pr merge "${GITHUB_HEAD_REF}" --merge --auto