name: Auto merge
on: pull_request
jobs:
    merge:
        # dependabot[bot]のプルリクエストのみを対象にする
        if: ${{ github.actor == 'dependabot[bot]' }} 
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub CLIのクレデンシャル
        steps:
            - uses: actions/checkout@v4
            - run: gh pr merge "${GITHUB_HEAD_REF}" --merge # GitHub CLIのコマンドを実行