name: Matrix
on: push
jobs:
  print:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # OSプロパティの定義
        version: [18,20]
    runs-on: ${{ matrix.os }} # OSプロパティの参照
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }} # versionプロパティの参照
      - run: echo "${RUNNERS_OS}" && node --version