  name: Share job data
  on: push
  jobs:
    before:
      runs-on: ubuntu-latest
      steps:
        - id: generate #ステップのID
          run: echo "result=Hello" >> ${GITHUB_OUTPUT} #ステップレベルの出力値
      outputs:
        result: ${{ steps.generate.outputs.result }} #ジョブレベルの出力値
    after:
      needs: [before]
      runs-on: ubuntu-latest
      steps:
        - env:
            RESULT: ${{needs.before.outputs.result}} #ジョブレベルの出力値を参照
          run: echo $RESULT