  name: Parallel jobs
  on: push
  jobs:
    first: # jobsキーへ複数のジョブを定義すれば、並列に実行される
      runs-on: ubuntu-latest
      steps:
        - run: sleep 10 && echo "First job"
    second:
      runs-on: ubuntu-latest
      steps:
        - run: sleep 10 && echo "Second job"
    third:
      runs-on: ubuntu-latest
      steps:
        - run: sleep 10 && echo "Third job"